# Generated by Django 5.0 on 2026-05-04 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buyers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=50, verbose_name='vehicle type')),
                ('vehicle_number', models.CharField(max_length=20, verbose_name='vehicle number')),
                ('license_number', models.CharField(max_length=30, verbose_name='license number')),
                ('is_available', models.BooleanField(default=True, verbose_name='available')),
                ('current_location', models.CharField(blank=True, max_length=100, null=True, verbose_name='current location')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='rating')),
                ('total_deliveries', models.IntegerField(default=0, verbose_name='total deliveries')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Delivery Partner',
                'verbose_name_plural': 'Delivery Partners',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='order number')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('assigned', 'Assigned to Delivery'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='status')),
                ('payment_status', models.CharField(choices=[('pending', 'Payment Pending'), ('completed', 'Payment Completed'), ('failed', 'Payment Failed')], default='pending', max_length=20, verbose_name='payment status')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='total amount')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='delivery fee')),
                ('delivery_address', models.TextField(verbose_name='delivery address')),
                ('delivery_location', models.CharField(blank=True, max_length=100, null=True, verbose_name='delivery location')),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True, verbose_name='estimated delivery')),
                ('actual_delivery', models.DateTimeField(blank=True, null=True, verbose_name='actual delivery')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('buyer_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='buyers.buyerrequest', verbose_name='buyer request')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('failed', 'Delivery Failed')], default='assigned', max_length=20, verbose_name='status')),
                ('pickup_location', models.CharField(blank=True, max_length=100, null=True, verbose_name='pickup location')),
                ('pickup_time', models.DateTimeField(blank=True, null=True, verbose_name='pickup time')),
                ('delivery_time', models.DateTimeField(blank=True, null=True, verbose_name='delivery time')),
                ('proof_of_delivery', models.ImageField(blank=True, null=True, upload_to='delivery_proofs/', verbose_name='proof of delivery')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('delivery_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='logistics.deliverypartner', verbose_name='delivery partner')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_assignment', to='logistics.order', verbose_name='order')),
            ],
            options={
                'verbose_name': 'Delivery Assignment',
                'verbose_name_plural': 'Delivery Assignments',
            },
        ),
    ]
