# Generated by Django 5.0 on 2026-05-04 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='product name')),
                ('category', models.CharField(choices=[('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('grains', 'Grains'), ('pulses', 'Pulses'), ('spices', 'Spices'), ('dairy', 'Dairy')], max_length=20, verbose_name='category')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='quantity')),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('quintal', 'Quintal'), ('ton', 'Ton'), ('piece', 'Piece'), ('dozen', 'Dozen')], default='kg', max_length=10, verbose_name='unit')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price per unit')),
                ('is_available', models.BooleanField(default=True, verbose_name='available')),
                ('harvest_date', models.DateField(blank=True, null=True, verbose_name='harvest date')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='location')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='farmer')),
            ],
            options={
                'verbose_name': 'Farmer Product',
                'verbose_name_plural': 'Farmer Products',
                'ordering': ['-created_at'],
            },
        ),
    ]
