# Generated by Django 5.0 on 2026-05-04 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='quantity requested')),
                ('unit', models.CharField(max_length=10, verbose_name='unit')),
                ('offered_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='offered price')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20, verbose_name='status')),
                ('delivery_address', models.TextField(verbose_name='delivery address')),
                ('delivery_location', models.CharField(blank=True, max_length=100, null=True, verbose_name='delivery location')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL, verbose_name='buyer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='farmers.farmerproduct', verbose_name='product')),
            ],
            options={
                'verbose_name': 'Buyer Request',
                'verbose_name_plural': 'Buyer Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
